/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package royalsovereign.label.ucc.scholastic;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author hkim
 */
public class ScholasticLabelPrintingFrame extends javax.swing.JFrame {
    
    String shipFrom, poNum, title, origin, ctnQty, ctnWeight, ISBN, destination;
    int numOfLabels;

    /**
     * Creates new form ScholasticLabelPrintingFrame
     */
    public ScholasticLabelPrintingFrame() {
        super("Scholatic Label Printing");
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ScholasticLabelPrintingFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ScholasticLabelPrintingFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ScholasticLabelPrintingFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ScholasticLabelPrintingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        numOfLabelsLabel = new javax.swing.JLabel();
        destinationTextField = new javax.swing.JTextField();
        destinationLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        ctnWeightTextField = new javax.swing.JTextField();
        ctnWeightLabel = new javax.swing.JLabel();
        ctnQtyTextField = new javax.swing.JTextField();
        ctnQtyLabel = new javax.swing.JLabel();
        originComboBox = new javax.swing.JComboBox();
        originLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        poNumberTextField = new javax.swing.JTextField();
        poNumberLabel = new javax.swing.JLabel();
        shipFromComboBox = new javax.swing.JComboBox();
        shipFromLabel = new javax.swing.JLabel();
        numOfLabelsSpinner = new javax.swing.JSpinner();
        buttonPanel = new javax.swing.JPanel();
        printLabelButton = new javax.swing.JButton();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        numOfLabelsLabel.setText("# of Labels:");

        destinationLabel.setText("Destination:");

        modelLabel.setText("Model:");

        ctnWeightLabel.setText("Ctn Weight:");

        ctnQtyLabel.setText("Ctn Qty:");

        originComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Made in China" }));

        originLabel.setText("Origin:");

        titleLabel.setText("Title:");

        poNumberTextField.setToolTipText("");

        poNumberLabel.setText("PO#:");

        shipFromComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NJ", "CA" }));

        shipFromLabel.setText("Ship From:");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(shipFromLabel)
                        .addGap(25, 25, 25)
                        .addComponent(shipFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(poNumberLabel)
                        .addGap(50, 50, 50)
                        .addComponent(poNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(52, 52, 52)
                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(originLabel)
                        .addGap(44, 44, 44)
                        .addComponent(originComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(ctnQtyLabel)
                        .addGap(34, 34, 34)
                        .addComponent(ctnQtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(ctnWeightLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ctnWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(modelLabel)
                        .addGap(44, 44, 44)
                        .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(destinationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(numOfLabelsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numOfLabelsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(shipFromLabel))
                    .addComponent(shipFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(poNumberLabel))
                    .addComponent(poNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(titleLabel))
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(originLabel))
                    .addComponent(originComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ctnQtyLabel))
                    .addComponent(ctnQtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ctnWeightLabel))
                    .addComponent(ctnWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(modelLabel))
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(destinationLabel))
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfLabelsLabel)
                    .addComponent(numOfLabelsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        printLabelButton.setText("Print Label");
        printLabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLabelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(printLabelButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printLabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLabelButtonActionPerformed
        // TODO add your handling code here:
        shipFrom = (String)shipFromComboBox.getSelectedItem();
        poNum = poNumberTextField.getText();
        title = titleTextField.getText();
        origin = (String)originComboBox.getSelectedItem();
        ctnQty = ctnQtyTextField.getText();
        ctnWeight = ctnWeightTextField.getText();
        ISBN = modelTextField.getText();
        destination = destinationTextField.getText();
        numOfLabels = (Integer)numOfLabelsSpinner.getValue();
        if (poNum.isEmpty() || title.isEmpty() || ctnQty.isEmpty() || ctnWeight.isEmpty() || ISBN.isEmpty() || destination.isEmpty() || numOfLabels==0){
            JOptionPane.showMessageDialog(this,"All Fields must be filled", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            ISBN = ISBN.replaceAll("[^0-9]", "");
            if(ISBN.isEmpty())
                ISBN = "0";
            while (ISBN.length()<13){
                ISBN = "0" + ISBN;
            }
            String output = "Ship From, PO#, Title, Country of Origin, CTN QTY, CTN Weight, ISBN10, ISBN13, Destination";
            for(int i=0; i<numOfLabels; i++){
                output += "\n";
                output += shipFrom + ",";
                output += poNum + ",";
                output += title + ",";
                output += origin + ",";
                output += ctnQty + ",";
                output += ctnWeight + ",";
                output += ISBN + ",";
                output += ISBN + ",";
                output += destination;
            }
            generateCSV(output);
        }
    }//GEN-LAST:event_printLabelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel ctnQtyLabel;
    private javax.swing.JTextField ctnQtyTextField;
    private javax.swing.JLabel ctnWeightLabel;
    private javax.swing.JTextField ctnWeightTextField;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel numOfLabelsLabel;
    private javax.swing.JSpinner numOfLabelsSpinner;
    private javax.swing.JComboBox originComboBox;
    private javax.swing.JLabel originLabel;
    private javax.swing.JLabel poNumberLabel;
    private javax.swing.JTextField poNumberTextField;
    private javax.swing.JButton printLabelButton;
    private javax.swing.JComboBox shipFromComboBox;
    private javax.swing.JLabel shipFromLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables

    private void generateCSV(String output) {
        String fileLocation = "//10.0.0.10/Public/IT/Label_Printing/bartender_edi/Scholastic.csv";
        try {
            FileWriter fw = new FileWriter(fileLocation);
            fw.append(output);
            fw.flush();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(ScholasticLabelPrintingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
